### ISSUE TITLE
Problem with snapshots and Tube Elite?

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#122]
Hi,

Using the disc image from http://bbcmicro.co.uk/game.php?id=2088 and b-em built from commit 99f09567b5823af728bd124fbb79a601e9a15012 on Ubuntu 18.04.5, if I set the emulator to Master Turbo mode, boot the disc, start a new game, hyperspace to Leesti, jump until I get to to the space station safe zone, fly towards the station and save a snapshot while the space station is on screen, if I load that snapshot back in I get a corrupt display - the space station seems to have exploded into a mass of unrelated lines:
![Screenshot at 2020-09-01 16-47-50](https://user-images.githubusercontent.com/7988240/91875397-57ffd680-ec73-11ea-8938-bdf3db9bf810.png)
Unfortunately this doesn't seem to happen if I take a snapshot with the space station on display after just launching from it at Lave.

I also note that - less dramatically, but perhaps easier to reproduce - if I launch from Lave space station, save a snapshot and immediately reload it, the colour of the line around the edge of the screen changes colour between yellow and magenta.

Sorry this is a slightly fuzzy report, I hope it won't be too hard to reproduce.

**Comment by SteveFosdick** [comment]
I can't see this one being easy to reproduce given my lack of skill at Elite.

Obviously there is something that saving a snapshot is not capturing, or something is happening immediately after the snapshot is restored that corrupts that.  I have tested saving with a tube processor running before but usually when the tube processor is doing something like running a BASIC interpreter so probably not actively driving the tube ULA at the point the snapshot is saved.  So maybe this is something like the state of status flags/interrupts around the Tube ULA.

**Comment by ZornsLemma** [comment]
For the less dramatic border change, all you need to do is start a new game and press (emulated) f0 to launch from the space station, then do the save state+restore state to (hopefully) see the border colour change. (Edit: By "border" I mean the lines Elite draws round the edge of the screen.)

The "exploded space station" does require knowing enough of the game to pilot the ship to Leesti space station.

**Comment by SteveFosdick** [comment]
How are you restoring the snapshot.  I have just discovered that naming the snapshot file on the command line does not work, even for running a BASIC program in the co-pro, while restoring it from the menu does work.  This is bound to be an order of execution thing.

**Comment by ZornsLemma** [comment]
I'm just using the "File->Load state..." menu option. I didn't even realise (though it does make sense) you could do it from the command line.

**Comment by SteveFosdick** [comment]
OK, I have solved the command-line loading - this was because there were some hooks for writing the CRTC registers but when loadstate restored them the hooks were not run.  I have pushed this to sf/newkeymap2.  Now loading state works from the command-line even with a co-pro.  Can you test to see if it solves the Elite issue or whether that is separate.

**Comment by ZornsLemma** [comment]
Thanks. Unfortunately I don't think it's helped - I still get the line around the screen edge changing from yellow to magenta if I save and load a snapshot just after launch. Actually it's not necessary to launch, you can do the save+load from the initial screen where it says "Load New Commander (Y/N)?" while showing a spinning ship.

I'll see if I can reproduce the exploding space station as well, if nothing else it would be good to have before and after screenshots.

For the record, this is using commit 54f1a6fd3dc1c793cb6716ac5fe1b16f3570ff31

**Comment by ZornsLemma** [comment]
Sorry, the problem with the exploding space station is still there too. Here's the before screenshot:
![Screenshot at 2020-09-03 00-16-48](https://user-images.githubusercontent.com/7988240/92046630-e743e180-ed7a-11ea-98c1-0cf1043a218a.png)
and here's the same view after doing a save state+load state from the File menu:
![Screenshot at 2020-09-03 00-17-09](https://user-images.githubusercontent.com/7988240/92046627-e6ab4b00-ed7a-11ea-9e4a-1a62002bfb29.png)
Note that this also shows the line around the screen edge changing from yellow to magenta.

**Comment by SteveFosdick** [comment]
Can you attach the snapshot file?  Now I know what it is supposed to look like I can perhaps trace/single-step what happens immediately after it is restored.

**Comment by ZornsLemma** [comment]
Sure! I've zipped it as github doesn't like it otherwise.
[elite-snapshot.zip](https://github.com/stardot/b-em/files/5165304/elite-snapshot.zip)

**Comment by SteveFosdick** [comment]
So this is the interesting part of the screen immediately the snapshot is loaded.  It looks odd presumably because the whole screen is in the mode with the higher number of colours rather than the higher resolution because the timer-based reprogramming of the 6845 has not yet started, but at least it looks like a ship.
![elite1](https://user-images.githubusercontent.com/1048671/92114415-b4383700-ede8-11ea-996e-eb614ef38599.png)

**Comment by SteveFosdick** [comment]
I have solved the issue with the colours.  This was a case of interchanging gree and blue when restoring the NuLA palette.

**Comment by SteveFosdick** [comment]
I have now solved the random lines problem too.  Looking at what happened immediately after the snapshot was restored it looks like the line drawing is happening by VDU codes being received over the tube so it seemed plain that what was going wrong was on the tube side and somehow it was getting the calculations wrong.

Then I spotted that there are two variables tracking the state the tube processor's boot ROM.  One, tube_romin, in the Tube ULA module (tube.c) and one, tuberomin, in the Tube 6502 modules (6502tube.c).  The one in the ULA code is used to decide if reading R1 from the parasite should page out the ROM or whether that has been done, and the one in 6502tube.c is actually used to decide whether to read from ROM or RAM.  The one in the Tube ULA code is restored as the snapshot is loaded but the one in 6502tube.c was not being restored leaving the ROM in the address space.

**Comment by SteveFosdick** [comment]
I have pushed a fix but I am not sure this two variables solution is ideal.  I'll have a look at what other tube processors do about their own ROMs.

**Comment by ZornsLemma** [comment]
Thanks Steve, I've just given this a try and I can no longer reproduce the colour changes or the exploding space station! Impressive work tracking this down with all these mixed up problems.

I don't know much about the internals of the tube hardware but I agree it seems a bit strange to have two variables tracking the state of the same thing - as this fix shows, it can be error prone duplicating things, but maybe it is helpful in some way I/we don't yet realise.

Anyway, I can now cheat^Wpractice docking at Elite using snapshots, which is great. Thanks again!

**Comment by SteveFosdick** [comment]
So a quick survey of how other tube processors handle ROMs:

- 32016 - handles this itself.
- 65816 - it is part of wider memory paging system.
- 6809 - uses a similar state variable but sets it internally.
- 80186 - no shortage of address space - ROM is not mapped out.
- ARM - no shortage of address space - ROM is not mapped out.
- Z80 - has its own flag which is set by a different event (access to memory above 0x8000).

Clearly there is a quirk of history here that, because the ROM is paged out on the 6502 by a write to the tube ULA, the state is saved with the Tube ULA contents rather than as part of the 6502 second processor state.  I suspect there might also have been a variable clash in the past with the 6502 way of paging out the ROM interfering with the Z80 way as these both use the same variable name, use of 'static' has not been consistent and up until recently the linker has been happy to coalesce multiple declarations of the same variable.

I'll see if I can tidy this up a bit.

**Comment by SteveFosdick** [comment]
The cleaned up version is in sf/newkeymap and master.

**Comment by ZornsLemma** [comment]
Thanks. It's not an area of b-em I feel super knowledgeable about, but the new code does look cleaner with the same variable name not being used in two different places.

Edit: Forgot to say that I can't reproduce the exploding space station bug with this new code, so that's good.

Unfortunately there still seems to be a snapshot related bug with tube Elite. This one is at least fairly easy to reproduce:

- Select Master Turbo emulation and boot the disc image from bbcmicro.co.uk mentioned above
- mount a blank DFS disc in drive 1
- say "N" to "Load New Commander" prompt
- press Space at "Press Space Or Fire" prompt
- hit emulated "@" key (on my PC keyboard this is "[") to get to the "disk access menu"
- press 2 for save
- type "X" for Commander's Name and press RETURN
- say "1" to "Which Drive?" question
- drive 1 whirs briefly and the game shows a screen titled "COMMANDER X"
- save the emulator state using the menu
- reload that emulator state using the menu
- press emulated "@" ("[") again and repeat the save process
- drive 1 whirs briefly but the game seems to be locked up and it doesn't return to the "COMMANDER X" screen

If you do that without the save/reload state steps, the second attempt at saving works fine.

**Comment by SteveFosdick** [comment]
Ok, this is looping in DFS:
```
9:8E1D: 30FC       BMI 8E1B    >s
9:8E1B: A5A2       LDA A2      >s
9:8E1D: 30FC       BMI 8E1B    >s
9:8E1B: A5A2       LDA A2      >s
```
This should be set by the NMI routine:
```
    0D00: 48         PHA         
    0D01: AD28 FE    LDA FE28    
    0D04: 29C7       AND #C7     
    0D06: C903       CMP #03     
    0D08: F02F       BEQ 0D39    
    0D0A: 29FC       AND #FC     
    0D0C: D004       BNE 0D12    
    0D0E: C6A5       DEC A5      
    0D10: D004       BNE 0D16    
    0D12: 85A2       STA A2      
    0D14: 68         PLA         
    0D15: 40         RTI         
```
Maybe it has dropped an NMI somewhere.

**Comment by SteveFosdick** [comment]
Looking at this:
```
07/09/2020 01:28:01 WARNING savestate: section p skipped
07/09/2020 01:28:19 DEBUG wd1770: write master-style ctrl 26
07/09/2020 01:28:19 DEBUG wd1770: reset 1770
07/09/2020 01:28:19 DEBUG wd1770: write track register, track=6c
07/09/2020 01:28:19 DEBUG wd1770: seek track=108
07/09/2020 01:28:20 DEBUG wd1770: fdc callback 13
07/09/2020 01:28:20 DEBUG wd1770: write track register, track=0e
07/09/2020 01:28:20 DEBUG wd1770: write sector register, sector=80
07/09/2020 01:28:20 DEBUG wd1770: start single write sector drive=1 side=0 track=14 sector=128 dens=0
07/09/2020 01:28:20 DEBUG wd1770: not found
```
DFS has not loaded the catalogue from disc 1 so presumably thinks it has a cached copy but is putting some nonense values into the registers on the WD1770 given that this is a standard DFS disc.

**Comment by SteveFosdick** [comment]
So, for comparison, this is what DFS does when saving commander 'X' for the first time on drive 1:
```
07/09/2020 15:48:36 DEBUG wd1770: write master-style ctrl 26
07/09/2020 15:48:36 DEBUG wd1770: reset 1770
07/09/2020 15:48:36 DEBUG wd1770: restore
07/09/2020 15:48:36 DEBUG wd1770: fdc callback 03
07/09/2020 15:48:36 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:36 DEBUG wd1770: restore
07/09/2020 15:48:36 DEBUG wd1770: fdc callback 03
07/09/2020 15:48:36 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:36 DEBUG wd1770: write sector register, sector=00
07/09/2020 15:48:36 DEBUG wd1770: start single read sector drive=1 side=0 track=0 sector=0 dens=0
07/09/2020 15:48:37 DEBUG wd1770: data i/o finished
07/09/2020 15:48:37 DEBUG wd1770: fdc callback 84
07/09/2020 15:48:37 DEBUG wd1770: write sector register, sector=01
07/09/2020 15:48:37 DEBUG wd1770: start single read sector drive=1 side=0 track=0 sector=1 dens=0
07/09/2020 15:48:37 DEBUG wd1770: data i/o finished
07/09/2020 15:48:37 DEBUG wd1770: fdc callback 80
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:37 DEBUG wd1770: write master-style ctrl 26
07/09/2020 15:48:37 DEBUG wd1770: reset 1770
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:37 DEBUG wd1770: restore
07/09/2020 15:48:37 DEBUG wd1770: fdc callback 03
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:37 DEBUG wd1770: write sector register, sector=00
07/09/2020 15:48:37 DEBUG wd1770: start single write sector drive=1 side=0 track=0 sector=0 dens=0
07/09/2020 15:48:37 DEBUG wd1770: data i/o finished
07/09/2020 15:48:37 DEBUG wd1770: fdc callback A4
07/09/2020 15:48:37 DEBUG wd1770: write sector register, sector=01
07/09/2020 15:48:37 DEBUG wd1770: start single write sector drive=1 side=0 track=0 sector=1 dens=0
07/09/2020 15:48:37 DEBUG wd1770: data i/o finished
07/09/2020 15:48:37 DEBUG wd1770: fdc callback A0
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:37 DEBUG wd1770: write master-style ctrl 26
07/09/2020 15:48:37 DEBUG wd1770: reset 1770
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:37 DEBUG wd1770: restore
07/09/2020 15:48:37 DEBUG wd1770: fdc callback 03
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
07/09/2020 15:48:37 DEBUG wd1770: write sector register, sector=02
07/09/2020 15:48:37 DEBUG wd1770: start single write sector drive=1 side=0 track=0 sector=2 dens=0
07/09/2020 15:48:37 DEBUG wd1770: data i/o finished
07/09/2020 15:48:37 DEBUG wd1770: fdc callback A4
07/09/2020 15:48:37 DEBUG wd1770: write track register, track=00
```
and this saving a second time from within the same session without saving/loading a snapshot:
```
07/09/2020 15:50:34 DEBUG wd1770: write master-style ctrl 26
07/09/2020 15:50:34 DEBUG wd1770: reset 1770
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: restore
07/09/2020 15:50:34 DEBUG wd1770: fdc callback 03
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: write sector register, sector=00
07/09/2020 15:50:34 DEBUG wd1770: start single read sector drive=1 side=0 track=0 sector=0 dens=0
07/09/2020 15:50:34 DEBUG wd1770: data i/o finished
07/09/2020 15:50:34 DEBUG wd1770: fdc callback 84
07/09/2020 15:50:34 DEBUG wd1770: write sector register, sector=01
07/09/2020 15:50:34 DEBUG wd1770: start single read sector drive=1 side=0 track=0 sector=1 dens=0
07/09/2020 15:50:34 DEBUG wd1770: data i/o finished
07/09/2020 15:50:34 DEBUG wd1770: fdc callback 80
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: write master-style ctrl 26
07/09/2020 15:50:34 DEBUG wd1770: reset 1770
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: restore
07/09/2020 15:50:34 DEBUG wd1770: fdc callback 03
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: write sector register, sector=00
07/09/2020 15:50:34 DEBUG wd1770: start single write sector drive=1 side=0 track=0 sector=0 dens=0
07/09/2020 15:50:34 DEBUG wd1770: data i/o finished
07/09/2020 15:50:34 DEBUG wd1770: fdc callback A4
07/09/2020 15:50:34 DEBUG wd1770: write sector register, sector=01
07/09/2020 15:50:34 DEBUG wd1770: start single write sector drive=1 side=0 track=0 sector=1 dens=0
07/09/2020 15:50:34 DEBUG wd1770: data i/o finished
07/09/2020 15:50:34 DEBUG wd1770: fdc callback A0
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: write master-style ctrl 26
07/09/2020 15:50:34 DEBUG wd1770: reset 1770
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: restore
07/09/2020 15:50:34 DEBUG wd1770: fdc callback 03
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
07/09/2020 15:50:34 DEBUG wd1770: write sector register, sector=02
07/09/2020 15:50:34 DEBUG wd1770: start single write sector drive=1 side=0 track=0 sector=2 dens=0
07/09/2020 15:50:34 DEBUG wd1770: data i/o finished
07/09/2020 15:50:34 DEBUG wd1770: fdc callback A4
07/09/2020 15:50:34 DEBUG wd1770: write track register, track=00
```

**Comment by SteveFosdick** [comment]
Fixed in commit https://github.com/stardot/b-em/commit/b4e3a717af3f37b331dc50eaac2509ba309b31ef

**Comment by ZornsLemma** [comment]
Thanks! I can see the fix was pretty simple, but it obviously took an awful lot of investigation to find out what fix was required. Much appreciated, I can confirm this works for me, and I can't reproduce the exploding space station bug either.

**Comment by SteveFosdick** [comment]
At 17:54 today I received an e-mail to say that exploding space station issue was still present along with a  before and after screenshot.  I think this is actually a delayed notification for a message much further up here.  Certainly there is no new comment here to that effect and my current sf/newkeymap2 branch does not show that problem.

On the previous comment, I ended up tracing through DFS and wondered how it was setting up a piece of workspace.  When I looked I saw it was not consistent with what the code appeared to be doing and guessed it might be ROM.  Once I knew that was the issue it was just a case of trying to work out why the ROM was not being paged in.

**Comment by ZornsLemma** [comment]
Yes, I think that's just a delayed notification - I certainly haven't seen anything to suggest the problem has re-appeared/not been fixed and I haven't sent you any messages or put comments on here saying I have. Thanks again for the work you put in on this! I'm having the odd little blast at Tube Elite every now and then when I have a few spare minutes, with snapshots it's something I can easily dip in and out of.
